config/routes.rb
Smtcoinc::Application.routes.draw do

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'
  resource :user_session, :only => [ :new, :create, :destroy ]

  resources :users do
    member do
      get 'delete'
    end
    resource :activation do
      member do
        get 'delete'
      end
    end
    resource :password, :only => [ :edit, :update ]
  end
  
  resources :user_verifications, :only => [ :show ]
  resources :password_resets
  resources :news, :as => :news_items, :controller => :news_items do
    member do
      get 'move'
    end
    collection do
      get 'fix_positions'
    end
  end
  match 'quote_requests/thanks' => 'quote_requests#thanks', :as => 'quote_request_thanks'
  resources :quote_requests
  resources :content_modules
  
  resources :mt_pdf_surveys
  resources :s3_uploads

  root :to => 'home#index'

end

app/models/quote_request.rb
class QuoteRequest < ApplicationModel
  belongs_to :quote_status
  validates_presence_of :name
  belongs_to :order_frequency
  
  def reply_to_email
    if (legal_email = Mail::Address.new(self.email)) and legal_email.domain.present?
      self.name_email
    else
      nil
    end
  end

  def name_email
    "\"#{self.name}\" <#{self.email}>"
  end
  
  scope :not_deleted, lambda {
    {
      :conditions => ['quote_requests.quote_status_id != ?', QuoteStatus.deleted.id]
    }
  }  
  
  def self.fields
    result = [:name, :company, :phone, :email, :address1, :address2, :city, :state, :zip, :country, :fax, :services, :other_service, :lead_time, :annual_use, :release_value, :order_frequency, :note, :created_at]
    forgotten = self.columns.map(&:name).map(&:to_sym) - [:id, :updated_at, :quote_status_id, :order_frequency_id, :subject] - result
    if forgotten.size > 0
      raise "QuoteRequest.fields is missing #{forgotten.join(', ')}"
    end
    result
  end
  
  def destroy
    self.update_attributes(:quote_status_id => QuoteStatus.deleted.id)
  end
  
  def services=(ids)
    write_attribute(:services, ids.reject { |i| i.blank? }.join(','))
  end
  
  def services
    if v = read_attribute(:services)
      v.split(',').map { |id| Service.find_by_id(id) }
    else
      []
    end
  end
  
  protected
  
    validate :some_way_to_contact
    def some_way_to_contact
      if self.phone.blank? and self.email.blank? and self.fax.blank?
        errors.add(:base, 'Please fill in a phone number or email address for us to contact you.')
      end
    end
  
    before_create :ensure_status
    def ensure_status
      self.quote_status ||= QuoteStatus.new_quote
    end

    after_create :send_email

    def send_email
      # Assume that only a spam bot would fill in the hidden subject field.
      if self.subject.blank?
        unless AppConfig.quote_request_recipients.blank?
          QuoteRequestMail.quote_request(self).deliver
        end
      else
        logger.info("Spam filtered quote request with subject: " + self.subject)
      end
    end
end

# == Schema Information
#
# Table name: quote_requests
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)
#  company            :string(255)
#  phone              :string(255)
#  email              :string(255)
#  address1           :string(255)
#  address2           :string(255)
#  state              :string(255)
#  city               :string(255)
#  zip                :string(255)
#  country            :string(255)
#  fax                :string(255)
#  services           :string(255)
#  lead_time          :string(255)
#  annual_use         :string(255)
#  release_value      :string(255)
#  order_frequency_id :integer(4)
#  note               :text
#  subject            :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  quote_status_id    :integer(4)      default(1)
#  other_service      :string(255)
#

app/controllers/quote_requests_controller.rb
class QuoteRequestsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  filter_access_to :all

  def new
    @quote_request = build_object
  end

  def create
    @quote_request = build_object

    if @quote_request.save
      redirect_to quote_request_thanks_url(:return_to => params[:return_to])
    else
      render :action => "new"
    end
  end

  def index
    @quote_requests = QuoteRequest.not_deleted.paginate(:all,
                                                        :order => 'updated_at desc',
                                                        :page => params[:page],
                                                        :per_page => 50)
  end
  
  def show
    @quote_request = current_object
  end
  
  def destroy
    current_object.destroy

    respond_to do |format|
      format.html { redirect_to(quote_requests_url) }
    end
  end

  protected

    def banner
      @banner || '/images/banners/quote_requests.jpg'
    end

#     layout :choose_layout
#     def choose_layout
#       if [:new].include?(action_name.to_sym)
#         'two_columns'
#       else
#         'application'
#       end
#     end
end

app/views/quote_requests/_form.html.erb
<%= raw store_referrer_as_return_to %>

<fieldset class="inputs" id="yourInfo">
	<h3>Your Information</h3>
	<ol>
		<li style="display:none" class="string optional" id="quote_request_subject_input"><label for="quote_request_subject">Subject</label><input id="quote_request_subject" maxlength="255" name="quote_request[subject]" size="50" type="text" /></li>
		<%= f.input :name, :as => :string %>
		<%= f.input :phone, :as => :string %>
		<%= f.input :fax, :as => :string %>
		<%= f.input :email, :as => :string %>
		<%= f.input :country, :as => :string %>
	</ol>
</fieldset>

<fieldset class="inputs" id="companyInfo">
	<h3>Company Information</h3>
	<ol>
		<%= f.input :company %>
		<%= f.input :address1 %>
		<%= f.input :address2 %>
		<%= f.input :city %>
		<%= f.input :state %>
		<%= f.input :zip %>
	</ol>
</fieldset>

<fieldset class="inputs" id="servicesInfo">
	<h3>Services Information</h3>
	<p>On what services would you like more information? (Check all that apply)</p>
	<ol>
		<%= f.input :services, :label => false, :as => :check_boxes, :collection => Service.all_except_other %>
	  <li id="quote_request_other_service_input">
		  <label for="quote_request_services_9">
			  <input id="quote_request_services_9" name="quote_request[services][]" value="9" type="checkbox"> Other
		  </label>
		 	<input id="quote_request_other_service" maxlength="255" name="quote_request[other_service]" type="text">
	  </li>
	</ol>
</fieldset>

<%= f.inputs :id => 'additionalQuest' do %>
	<%= f.input :lead_time, :label => 'What is your lead time?' %>
	<%= f.input :annual_use %>
	<%= f.input :release_value %>
	<%= f.input :order_frequency %>
	<%= f.input :note, :label => 'Other details, specifications and notes' %>
<% end %>

app/views/quote_requests/index.html.erb
<% title "Quote Requests" %>

<%= will_paginate @quote_requests %>

<table class="data">
  <thead>
    <tr>
			<th><%= QuoteRequest.human_attribute_name(:created_at) %></th>
			<th><%= QuoteRequest.human_attribute_name(:email) %></th>
			<th><%= QuoteRequest.human_attribute_name(:name) %></th>
			<th><%= QuoteRequest.human_attribute_name(:company) %></th>
			<th><%= QuoteRequest.human_attribute_name(:phone) %></th>
			<th><%= QuoteRequest.human_attribute_name(:note) %></th>
			<td />
    </tr>
  </thead>
  <tbody>
  <% @quote_requests.each do |quote_request| %>
    <tr>
      <td><%= link_to quote_request.created_at.strftime('%B %d, %Y'), quote_request_path(quote_request) %></td>
      <td><%=h quote_request.email %></td>
      <td><%=h quote_request.name %></td>
      <td><%=h quote_request.company %></td>
      <td><%=h quote_request.phone %></td>
      <td><%=h quote_request.note[0..31] %></td>
      <td>
				<%= link_to 'Delete', quote_request_path(quote_request), :method => 'delete', :confirm => 'Are you sure?'%>
			</td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @quote_requests %>

app/views/quote_requests/new.html.erb
<% cm = content_module(:quote_request) %>

<div id="maincopy">
	<h2><%= title cm.title %></h2>
	<%= raw cm.content %>

  <h2>Request Form</h2>
	<% semantic_form_for @quote_request do |f| %>
		<%= f.error_messages %>
	  <%= render :partial => "form", :locals => {:f => f} %>
		<div class="clear"></div>
	  <%= f.buttons do %>
	    <%= f.commit_button 'SUBMIT' %>
		<% end %>
	<% end %>
</div>

app/views/quote_requests/show.html.erb
<% title "Quote request from: #{@quote_request.name_email}" %>

-------- Quote Request -------------
<p>
From:  <%= @quote_request.name_email %><br />
To:    LXD<br />
Sent:  <%= @quote_request.created_at %><br />
</p>
<br />
<p>
	<% (QuoteRequest.fields - [:name, :email, :created_at, :note]).each do |field| %>
	<% if (value = @quote_request.send(field)).present? %>
	<%= QuoteRequest.human_attribute_name(field)%>:
		<% if value.is_a?(Array) %>
		<%= raw value.join(', ') %>
		<% else %>
		<%= value %>
		<% end %><br/>
	<% end %>
	<% end %>
</p>

<%= simple_format @quote_request.note %>

<p>
	<%= link_to('Back', quote_requests_path) %>
</p>

app/views/quote_requests/thanks.html.erb
<% title 'Thank You For Contacting Us' %>

<h3>Thank you for contacting us!  We've received you're request for a quote and will get back to you soon!</h3>

<% if return_to = params[:return_to] %>
	<br />
	<h4>
		<%= link_to '<< Go back', return_to %>
	</h4>
<% end %>