config/routes.rb
Smtcoinc::Application.routes.draw do

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'
  resource :user_session, :only => [ :new, :create, :destroy ]

  resources :users do
    member do
      get 'delete'
    end
    resource :activation do
      member do
        get 'delete'
      end
    end
    resource :password, :only => [ :edit, :update ]
  end
  
  resources :user_verifications, :only => [ :show ]
  resources :password_resets
  resources :news, :as => :news_items, :controller => :news_items do
    member do
      get 'move'
    end
    collection do
      get 'fix_positions'
    end
  end
  match 'quote_requests/thanks' => 'quote_requests#thanks', :as => 'quote_request_thanks'
  resources :quote_requests
  resources :content_modules
  
  resources :mt_pdf_surveys
  resources :s3_uploads

  root :to => 'home#index'

end

app/models/user.rb
class User < ApplicationModel
  model_stamper
  acts_as_authentic do |c|
    c.validate_password_field = true
    c.maintain_sessions = false
  end
  belongs_to :user_role
  belongs_to :user_status
  attr_protected :password, :password_confirmation, :user_role, :user_status
  validates_presence_of :first_name, :last_name, :email, :user_status, :user_role

  has_many :user_messages, :dependent => :delete_all
  has_many :messages, :through => :user_messages

  belongs_to :notification_preference

  attr_accessor :current_password
  scope :active, :conditions => { :user_status_id => UserStatus.active.id }
  
  # This method is necessary method for declarative_authorization to determine roles
  # Roles returns e.g. [:admin]
  def role_symbols
    [self.user_role.downcase.to_sym]
  end
  
  # For Declarative Auth.
  def role_symbols
    @role_symbols ||= (!user_role.nil?) ? [user_role.name.downcase.to_sym] : []
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def name_and_email
    "#{full_name} #{email}".strip
  end

  def first_name_or_last
    first_name.present? ? first_name : last_name
  end

  def email_address_with_name
    if full_name.present?
      "\"#{full_name}\" #{email}"
    else
      email
    end
  end

  def to_trace
    "#{user_role.name} #{id} '#{full_name}'"
  end

  def destroy
    self.update_attributes(:user_status_id => UserStatus.deleted.id)
  end

  def deliver_verification_instructions!
    reset_perishable_token!
    UserVerification.verification_instructions(self).deliver
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetNotifier.password_reset_instructions(self).deliver
  end

  def verify!
    self.update_attributes(:user_status_id => UserStatus.active.id)
  end

  def self.robo_mailer
    find_by_email(AppConfig.email_address)
  end

  def self.new_from_email(email)
    user = new(:email => email)
    user.save(false)
    user
  end

  protected

    before_validation :set_default_status_and_role, :on => :create
    def set_default_status_and_role
      self.user_role_id ||= UserRole.user.id
      self.user_status_id ||= UserStatus.unconfirmed.id
    end
end

# == Schema Information
#
# Table name: users
#
#  id                      :integer(4)      not null, primary key
#  first_name              :string(255)
#  last_name               :string(255)
#  notification_preference :integer(4)
#  photo_file_name         :string(255)
#  photo_content_type      :string(255)
#  photo_file_size         :integer(4)
#  user_status_id          :integer(4)
#  user_role_id            :integer(4)
#  email                   :string(255)
#  crypted_password        :string(255)
#  password_salt           :string(255)
#  persistence_token       :string(255)
#  single_access_token     :string(255)
#  perishable_token        :string(255)
#  login_count             :integer(4)      default(0)
#  failed_login_count      :integer(4)      default(0)
#  last_request_at         :datetime
#  current_login_at        :datetime
#  last_login_at           :datetime
#  current_login_ip        :string(255)
#  last_login_ip           :string(255)
#  created_at              :datetime
#  updated_at              :datetime
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  filter_access_to_defaults
  before_filter :require_login, :only => [:index, :show]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = current_object
  end

  # GET /users/new
  def new
    @user = build_object
  end

  # GET /users/1/edit
  def edit
    @user = current_object
  end

  # POST /users
  def create
    @user = build_object
    respond_to do |format|
      if @user.save
        format.html {
          if current_user
            flash[:notice] = 'User was successfully created.'
            redirect_to(@user)
          else
            flash[:notice] = 'A verification email has been sent.'
            @user.deliver_verification_instructions!
            redirect_to root_url(:nocache=>1)
          end
        }
        format.json { render :nothing => true, :status => :created }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  def update
    @user = current_object

    if @user.save
      flash[:notice] = 'User was successfully updated.'
      redirect_to(@user)
    else
      render :action => "edit"
    end
  end

  # GET /users/1/delete
  def delete
    @user = User.find(params[:id])
    @user.delete
    redirect_to(users_url)
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.id == current_user.id
      current_user_session.destroy
      flash[:notice] = "Account deleted"
      redirect_to(root_url(:nocache=>1))
    else
      redirect_to(users_url)
    end
  end

  protected

    def current_object
      @current_object ||= get_user_object(:find)
    end

    def build_object
      @current_object ||= get_user_object(:new)
    end

    def get_user_object(method)
      if @current_object.nil?
        user_params = params[:user] || {}
        user_role_id = user_params.delete(:user_role_id)
        user_status_id = user_params.delete(:user_status_id)
        user_password = user_params.delete(:password)
        user_password_confirmation = user_params.delete(:password_confirmation)
        @current_object = method == :new ? User.new(user_params) : User.find(params[:id])
        if permitted_to? :manage, @current_object
          @current_object.user_status_id = user_status_id if user_status_id.present?
          @current_object.user_role_id = user_role_id if user_role_id.present?
        end
        if user_password
          @current_object.password = user_password
          @current_object.password_confirmation = user_password_confirmation
        end
      end
      @current_object
    end
end

app/views/users/_form.html.erb
<% f.inputs do %>
  <%= f.input :first_name %> 
  <%= f.input :last_name %> 
  <%= f.input :email %>
  <% if permitted_to?(:set_role, @user) %>
  <%= f.input :user_role %>
  <%= f.input :user_status %>
  <% end %>
	<% if @user.new_record? %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
	<% end %>
<% end %>

<% f.buttons do %>
  <%= f.commit_button %>
  <%= f.cancel_link %>
	<% if !@user.new_record? and permitted_to?(:delete) %>
	<li class="link"><%= link_to "Delete From Database", delete_user_url(@user), :confirm => 'Are you sure?' %></li>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<% title 'Edit User' %>

<% semantic_form_for @user, :url => user_path do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/users/index.html.erb
<% title "Users" %>

<%= link_to 'New User', new_user_path %>

<table class="data">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th>Status</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.full_name, user_path(user) %></td>
      <td><%= user.email %></td>
      <td><%= user.user_role.name %></td>
      <td><%= user.user_status.name %></td>
      <td>
				<% links = [] %>
				<% if permitted_to? :manage, :users %>
				<% links.push link_to("Edit", edit_user_path(user)) %> 
				<% end %>
				<%= raw links.join(' | ')%>
			</td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% title 'New User' %>
<% semantic_form_for @user do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/users/show.html.erb
<% title @user.full_name  %>

<% links = [] %>
<% if permitted_to? :manage, @user %>
<% links.push link_to("Edit", edit_user_path(@user)) %> 
<% links.push link_to('Cancel Account', user_path(@user), :method => :delete, :confirm => 'Are you sure?') %>
<% links.push link_to('Change Password', edit_user_password_path(@user)) %>
<% end %>
<%# if permitted_to? :switch, :users %>
<%# links.push link_to('Switch', switch_path(@user.email)) %>
<%# end %>
<% if permitted_to?(:delete) %>
<% links.push link_to "Delete From Database", delete_user_url(@user), :confirm => 'Are you sure?' %>
<% end %>
<%= raw links.join(' | ')%>

<table class="data" border="0" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Name</td>
      <td><%= @user.full_name %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Status</td>
      <td><%= @user.user_status.name %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Created</td>
      <td><%= @user.created_at %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Email</td>
      <td><%= @user.email %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Role</td>
      <td><%= @user.user_role.name %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Login Count</td>
      <td><%= comma @user.login_count %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Failed Login Count</td>
      <td><%= comma @user.failed_login_count %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Last Request At</td>
      <td><%= @user.last_request_at %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Current Login At</td>
      <td><%= @user.current_login_at %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Last Login At</td>
      <td><%= @user.last_login_at %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Current Login IP</td>
      <td><%= @user.current_login_ip %></td>
    </tr>
	  <tr class="<%= cycle('odd','even') %>">
      <td>Last Login IP</td>
      <td><%= @user.last_login_ip %></td>
    </tr>
	</tbody>
</table>