config/routes.rb
Smtcoinc::Application.routes.draw do

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'
  resource :user_session, :only => [ :new, :create, :destroy ]

  resources :users do
    member do
      get 'delete'
    end
    resource :activation do
      member do
        get 'delete'
      end
    end
    resource :password, :only => [ :edit, :update ]
  end
  
  resources :user_verifications, :only => [ :show ]
  resources :password_resets
  resources :news, :as => :news_items, :controller => :news_items do
    member do
      get 'move'
    end
    collection do
      get 'fix_positions'
    end
  end
  match 'quote_requests/thanks' => 'quote_requests#thanks', :as => 'quote_request_thanks'
  resources :quote_requests
  resources :content_modules
  
  resources :mt_pdf_surveys
  resources :s3_uploads

  root :to => 'home#index'

end

app/models/news_item.rb
class NewsItem < ApplicationModel
  belongs_to :status
  belongs_to :news_type
  belongs_to :show_image_mode
  acts_as_list
  after_create :move_to_top
  BUCKET = 'mtwa'
  has_attached_file( :image, :whiny => false,
                     :styles => {:show => '200>', :index => '100>', :edit => '100>', :thumbnail => '100>', :medium => '400>', :large => '600>' },
                     :storage => :s3,
                     :s3_credentials => "#{Rails.root}/config/s3.yml",
                     :url => ':s3_domain_url',
                     :path => ":class/:attachment/:id/:style/:basename.:extension",
                     :bucket => BUCKET )
  has_attached_file( :attachment,
                     :storage => :s3,
                     :s3_credentials => "#{Rails.root}/config/s3.yml",
                     :url => ':s3_domain_url',
                     :path => ":class/:attachment/:id/:style/:basename.:extension",
                     :bucket => BUCKET )

  scope :by_position, :order => :position
  after_create :move_to_top

  scope :not_deleted, lambda {
    {
      :conditions => ['news_items.status_id != ?', Status.deleted.id]
    }
  }

  scope :on_home_page, :conditions => { :home_page => true }
  
  def destroy
    self.update_attributes(:status_id => Status.deleted.id)
    self.remove_from_list
  end
  
  def move!(direction)
    case direction
    when 'up'
      self.move_higher
    when 'down'
      self.move_lower
    when 'top'
      self.move_to_top
    when 'bottom'
      self.move_to_bottom
    end
  end

  protected

    clean_urls :image_url
    
    after_update :reposition
    def reposition
      if !self.status.deleted? and self.position.nil?
        self.insert_at(1)
      end
    end

end

# == Schema Information
#
# Table name: news_items
#
#  id                      :integer(4)      not null, primary key
#  status_id               :integer(4)      default(1)
#  news_type_id            :integer(4)      default(1)
#  position                :integer(4)
#  home_page               :boolean(1)      default(TRUE)
#  title                   :string(255)
#  summary                 :text
#  body                    :text
#  location                :string(255)
#  publish_date            :datetime
#  image_caption           :string(255)
#  image_url               :string(1024)
#  image_file_name         :string(255)
#  image_content_type      :string(255)
#  image_file_size         :integer(4)
#  image_updated_at        :datetime
#  show_image_mode_id      :integer(4)      default(2)
#  attachment_title        :string(255)
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer(4)
#  attachment_updated_at   :datetime
#  creator_id              :integer(4)
#  updater_id              :integer(4)
#  created_at              :datetime
#  updated_at              :datetime
#

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  filter_access_to_defaults

  def index
    cache_control
    respond_to do |f|
      f.html do
        @news_items = NewsItem.not_deleted.with_permissions_to(:read).by_position
        @news_items = @news_items.paginate(:all,
                                           :page => params[:page],
                                           :per_page => 50)
      end
    end
  end

  def show
    @news_item = current_object
  end

  def new
    @news_item = build_object
  end

  def edit
    @news_item = current_object
  end

  def create
    @news_item = build_object

    if @news_item.save
      flash[:notice] = 'News Item was successfully created.'
      if params[:commit] == 'Save & Edit'
        redirect_to(edit_news_item_url(@news_item, :return_to => params[:return_to]))
      else
        redirect_back_or_default(news_item_url(@news_item))
      end
    else
      render :action => "new"
    end
  end

  def update
    @news_item = current_object

    respond_to do |format|
      if @news_item.update_attributes(params[:news_item])
        flash[:notice] = 'News Item was successfully updated.'
        format.html {
          if params[:commit] == 'Save & Edit'
            redirect_to(edit_news_item_url(@news_item, :return_to => params[:return_to]))
          else
            redirect_back_or_default(news_item_url(@news_item))
          end
        }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def move
    @news_item = current_object
    @news_item.move!(params[:direction])
    redirect_back_or_default(news_items_url)
  end

  def fix_positions
    position = 0
    changed = 0
    @news_items = NewsItem.not_deleted.by_position.each do |news_item|
      news_item.position = (position += 1)
      if news_item.changed?
        changed += 1
        news_item.save
      end
    end
    flash[:notice] = "Repositioned #{changed} News Items"
    redirect_to news_items_url
  end

  def destroy
    @news_item = current_object
    @news_item.destroy

    respond_to do |format|
      format.html { redirect_to(news_items_url) }
    end
  end

  protected

    # layout :choose_layout
    # def choose_layout
    #   if [:new, :edit].include?(action_name.to_sym)
    #     'application'
    #   else
    #     'two_columns'
    #   end
    # end

end

app/helpers/news_item_helper.rb
module NewsItemHelper
  def prefixed_content(news_item, content_type)
    content = if content_type == :summary
      txt = news_item.summary.present? ? news_item.summary : news_item.body
      if news_item.body.present? and (txt =~ /^<p>(.+)<\/p>$/m)
        link_text = "<a href=\"#{news_item_url(news_item)}\">&raquo; Read More</a>"
        "<p>#{$1}<br />#{link_text}</p>"
      else
        txt
      end
    else
      news_item.body.present? ? news_item.body : news_item.summary
    end
    prefix = []
    prefix.push news_item.location if news_item.location.present?
    # prefix.push "(#{news_item.publish_date.to_s(:news_item)})" if news_item.publish_date.present?
    content = if prefix.size > 0
      content.sub('<p>', "<p> <strong>#{prefix.join(' ')}</strong> &ndash; ")
    else
      content
    end
    if (content_type == :summary) and news_item.attachment? and news_item.summary.blank?
      attachment_link = link_to news_item.attachment_title, news_item.attachment.url
      if content =~ /^<p>(.+)<\/p>$/m
        content = '<p>' + $1 + ' ' + attachment_link + '</p>'
      else
        content << '<p>' + attachment_link + '</p>'
      end
    end
    content
  end
end

app/views/news_items/_form.html.erb
<%= raw store_referrer_as_return_to %>
<% f.inputs do %>
  <%= f.input :status, :collection => Status.all, :required => true %>
  <%= f.input :news_type, :collection => NewsType.all, :required => true %>
	<li class="boolean optional" id="news_item_home_page_input">
		<label for="news_item_home_page"><%= NewsItem.human_attribute_name(:home_page)%></label>
		<%= f.check_box(:home_page) %>
	</li>
  <%= f.input :title, :required => true %>
  <%= f.input :summary, :input_html => {:class => 'mceEditor'} %>
  <%= f.input :body, :input_html => {:class => 'mceEditor'}, :required => true %>
  <%= f.input :location, :required => true %>
  <%= f.input :publish_date, :as => :calendar, :size => 10, :required => true %>
  <%= f.input :image, :as => :attachment %>
	<%= f.input :image_url %>
  <%= f.input :show_image_mode, :collection => ShowImageMode.all %>
  <%= f.input :attachment, :as => :attachment %>
  <%= f.input :attachment_title %>
<% end %>

app/views/news_items/_short_show.html.erb
<% if news_item.image? and (news_item.show_image_mode.small? or news_item.show_image_mode.large?) %>
<%= link_to image_tag(news_item.image.url(:thumbnail)), news_item_url(news_item)  %>
<% end %>
<h4><%= link_to_if news_item.body.present?, news_item.title, news_item_url(news_item) %>
	<% if news_item.publish_date.present? %>
	<span class="date"><%= news_item.publish_date.to_s(:post) %></span>
	<% end %>
</h4>
<%= raw prefixed_content(news_item, :summary) %>

app/views/news_items/_show.html.erb
<div class="post">
	<% if permitted_to? :manage, :news_items %>
	<div class="toolbar">
		<ul class="actions">
			<% if news_item.status.draft? %>
			<li>Draft:</li>
			<% end %>
			<li><%= link_to 'Edit', edit_news_item_path(news_item, :return_to => request.url) %></li>
			<% if news_item.status.deleted? %>
			<li>Deleted</li>
			<% else %>
			<li><%= link_to 'Delete', news_item_path(news_item), :confirm => 'Are you sure?', :method => :delete %></li>
			<li><%= link_to 'Back', news_items_path %></li>
			<li>
				<i>[ move: 
	      <% unless news_item.first? %>
	        <%= link_to "up", move_news_item_path(news_item, :direction => 'up') %> 
	        <%= link_to "top", move_news_item_path(news_item, :direction => 'top') %>
	      <% end %>
	      <% unless news_item.last? %>
		      <%= link_to "down", move_news_item_path(news_item, :direction => 'down') %>
		      <%= link_to "bottom", move_news_item_path(news_item, :direction => 'bottom') %>
	      <% end %>
	      ]</i>   
	     </li>
			<% end %>
		</ul>
	</div>
	<% end %>
	
	<% if news_item.image? and news_item.show_image_mode.small? %>
	<% it = image_tag(news_item.image.url(:show))  %>
	<%= news_item.image_url.present? ? link_to(it, news_item.image_url) : it %>
	<% end %>
	<h2><%= news_item.title %></h2>
	<%= raw prefixed_content(news_item, :body) %>
	<% if news_item.attachment? %>
	<p><%= link_to news_item.attachment_title, news_item.attachment.url %></p>
	<% end %>	
	<% if news_item.image? and news_item.show_image_mode.large? %>
	<p>
	<% it = image_tag(news_item.image.url(:large), :width => '534')  %>
	<%= news_item.image_url.present? ? link_to(it, news_item.image_url) : it %>
	</p>
	<% end %>
</div><!-- post -->

app/views/news_items/atom.xml.erb
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title><%= AppConfig.company_name %></title>
    <link href="http://lxdinc.com/news/atom.xml" rel="self"/>
    <link href="http://open.wested.org/"/>
    <updated>{{ site.time | date_to_xmlschema }}</updated>
    <id>http://open.wested.org/</id>
    
    {% for post in site.posts %}
    <entry>
        <title>{{ post.title | h }}</title>
        {% comment %}
        {% for category in post.categories %}
        <category term="{{category}}" scheme="http://www.sixapart.com/ns/types#tag" />
        {% endfor %}
        {% endcomment %}
        <link href="http://open.wested.org{{ post.url }}"/>
        <updated>{{ post.date | date_to_xmlschema }}</updated>
        <id>open.wested.org:{{ post.id }}</id>
        <content type="html">{{ post.content | h}}</content>
        <author>
            <name>{{post.author_name}}</name>
            <uri>{{post.author_uri}}</uri>
        </author>
    </entry>
    {% endfor %}
</feed>

app/views/news_items/edit.html.erb
<% title 'Editing News Item' %>

<% semantic_form_for @news_item, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <%= render :partial=>'form', :locals =>{:f=>f} %>
  <% f.buttons do %>
	  <%= f.commit_button 'Save' %>
	  <%= f.commit_button 'Save & Edit' %>
    <li class="link"><%= link_to 'Cancel', (params[:return_to] || news_items_url) %></li>
    <li class="link"><%= link_to 'Delete', news_item_path(@news_item), :confirm => 'Are you sure?', :method => :delete %></li>
  <% end %>
<% end %>

app/views/news_items/index.html.erb
<% title 'SMT News' %>

<% if permitted_to? :manage, :news_items %>
<%= link_to 'Create News Item', new_news_item_url %> |
<%= link_to 'Fix Positions', fix_positions_news_items_url %>
<% end %>

<%= will_paginate @new_items %>
<div id="maincopy">
	<h2>News</h2>
<% @news_items.each do |news_item| %>
	<%= render 'show', :news_item => news_item %>
<% end %>
</div><!-- maincopy -->
<%= will_paginate @news_items %>

app/views/news_items/new.html.erb
<% title 'News Item' %>

<% semantic_form_for @news_item, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <%= render :partial=>'form', :locals =>{:f=>f} %>
  <% f.buttons do %>
    <%= f.commit_button 'Save' %>
    <%= f.commit_button 'Save & Edit' %>
    <li class="link"><%= link_to 'Cancel', (params[:return_to] || news_items_url) %></li>
  <% end %>
<% end %>

app/views/news_items/show.html.erb
<% title (title_txt = 'SMT ' + @news_item.news_type.name) %>
<% meta_title @news_item.title %>
<%= render 'show', :news_item => @news_item %>