config/routes.rb
Smtcoinc::Application.routes.draw do

  match 'login' => 'user_sessions#new', :as => 'login'
  match 'logout' => 'user_sessions#destroy', :as => 'logout'
  resource :user_session, :only => [ :new, :create, :destroy ]

  resources :users do
    member do
      get 'delete'
    end
    resource :activation do
      member do
        get 'delete'
      end
    end
    resource :password, :only => [ :edit, :update ]
  end
  
  resources :user_verifications, :only => [ :show ]
  resources :password_resets
  resources :news, :as => :news_items, :controller => :news_items do
    member do
      get 'move'
    end
    collection do
      get 'fix_positions'
    end
  end
  match 'quote_requests/thanks' => 'quote_requests#thanks', :as => 'quote_request_thanks'
  resources :quote_requests
  resources :content_modules
  
  resources :mt_pdf_surveys
  resources :s3_uploads

  root :to => 'home#index'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  private
    validate :check_if_verified
    def check_if_verified
      case attempted_record.try(:user_status_id)
      when UserStatus.active.id
        # Success!
      when UserStatus.suspended.id
        errors.add(:base, "This account has been suspended")
      when UserStatus.unconfirmed.id
        errors.add(:base, "This account not yet been verified")
      else
        errors.add(:base, "This account does not exist")
      end
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  before_filter :require_not_logged_in, :only => [:new,:create]

  def new
    @user_session ||= UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful"
      redirect_back_or_default root_url(:nocache=>1)
    else
      flash.now[:error] = "Login unsuccessful"
      render :action => 'new'
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default login_url
  end

end

app/views/user_sessions/_login.html.erb
<div>
  <h2>Login</h2>
	<% @user_session ||= UserSession.new %>
	<%#= error_messages_for :user_session %>
	<%= @user_session.errors['base']%>
  <% semantic_form_for @user_session, :url => user_session_path do |f| %>
    <%= f.inputs do %>
      <%= f.input :email, :required => true %>
      <%= f.input :password, :required => true, :wrapper_html => { :class => 'string' } %>
      <%= f.input :remember_me, :as => :boolean, :required => false %>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button "Login" %>
			<li class="link"><%= link_to "Forgot Password?", new_password_reset_url %></li>
    <% end %>
  <% end %>
</div>

app/views/user_sessions/new.html.erb
<%= render :partial => 'user_sessions/login' %>